name: Migrate GitLab repository
run-name: Migrate repository from GitLab to GitHub by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      run-migrate:
        description: Migrate repository
        required: true
        type: boolean
      gitlab-project-id:
        description: |
          GitLab project ID
        required: false
        type: string

jobs:
  gitlab:
    name: GitLab Repository
    runs-on: ubuntu-latest
    env:
      GITLAB_API_URL: "https://gitlab.com/api/v4/projects"
      GITLAB_AUTH_TOKEN: ${{ secrets.GL_AUTH_TOKEN }}
      GITLAB_PROJECT_ID: ${{ inputs.gitlab-project-id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup arkade
        uses: alexellis/arkade-get@master
        with:
          jq: latest

      - name: Check GitLab repository
        id: gitlab-repo-exists
        run: |
          echo "GITLAB_OUTPUT=$(curl -H "PRIVATE-TOKEN: ${{ env.TOKEN }}" -s "${{ env.URL }}/${{ env.ID }}" | jq -r '.name')" >> $GITHUB_OUTPUT
        shell: bash
        env:
          ID: ${{ env.GITLAB_PROJECT_ID }}
          URL: ${{ env.GITLAB_API_URL }}
          TOKEN: ${{ env.GITLAB_AUTH_TOKEN }}

      - name: Debug GitLab repository name
        run: |
          echo "GitLab repository name: ${{ steps.gitlab-repo-exists.outputs.GITLAB_OUTPUT }}"

