name: Migrate GitLab repository
run-name: Migrate repository from GitLab to GitHub by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      run-migrate:
        description: Migrate repository
        required: true
        type: boolean
      gitlab-project-id:
        description: |
          GitLab project ID
        required: false
        type: string

jobs:
  fetch-gitlab:
    name: GitLab Repository
    runs-on: ubuntu-latest
    env:
      GITLAB_API_URL: "https://gitlab.com/api/v4/projects"
      GITLAB_AUTH_TOKEN: ${{ secrets.GL_AUTH_TOKEN }}
      GITLAB_PROJECT_ID: ${{ inputs.gitlab-project-id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup arkade
        uses: alexellis/arkade-get@master
        with:
          jq: latest

      - name: Fetch information from the GitLab repository
        id: gitlab-fetch-data
        run: |
          echo "REPO_NAME=$(curl -H "PRIVATE-TOKEN: ${{ env.TOKEN }}" -s "${{ env.REPO_URL }}" | jq -r '.name')" >> $GITHUB_OUTPUT
          echo "CLONE_URL=$(curl -H "PRIVATE-TOKEN: ${{ env.TOKEN }}" -s "${{ env.REPO_URL }}" | jq -r '.http_url_to_repo')" >> $GITHUB_OUTPUT
        shell: bash
        env:
          TOKEN: ${{ env.GITLAB_AUTH_TOKEN }}
          REPO_URL: ${{ env.GITLAB_API_URL }}/${{ env.GITLAB_PROJECT_ID }}

      - name: Debug GitLab repository name
        run: |
          echo "GitLab repository name: ${{ steps.gitlab-fetch-data.outputs.REPO_NAME }}"
          echo "GitLab repository clone url: ${{ steps.gitlab-fetch-data.outputs.CLONE_URL }}"

      - name: Clone GitLab repository
        id: gitlab-clone-repo
        run: |
          git clone --bare ${{ env.SOURCE_REPO_URL }} -q
          echo "BARE_REPO_DIR=$(echo "${{ env.SOURCE_REPO_URL }}" | grep -oE '(/[^/]+){1}$' | cut -d "/" -f 2)" >> $GITHUB_OUTPUT
        env:
          SOURCE_REPO_URL: ${{ steps.gitlab-fetch-data.outputs.CLONE_URL }}

      - name: Debug bare repository
        run: |
          echo "${{ env.BARE_DIR }}"
          cd "${{ env.BARE_DIR }}" || exit
          ls -lthr
        env:
          BARE_DIR: ${{ steps.gitlab-clone-repo.outputs.BARE_REPO_DIR }}



